config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root controller: :articles, action: :index

  resources :articles
  namespace :superuser do
    get :/, controller: :articles, action: :index
    resources :articles do
	  	put :active
	  end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/amin_user.rb
class AminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	paginates_per 20
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :category

  has_attached_file                 :image, styles: { thumb: "540x322#" }, default_url: ':missing'
  validates_attachment_size         :image, :in => 0.megabytes..2.megabytes, message: 'The image must be smaller 2Mb'
  validates_attachment_content_type :image, content_type: ['image/jpeg', 'image/png'], message: 'Please select image png or jpg'

  delegate :name, to: :category, prefix: true


  def self.search(search)
	  if search
	    Article.where('title ILIKE ?', "%#{search}%")
	  else
	    Article.all
	  end
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all.where(active: true).search(params[:search]).order(:created_at).page(params[:page])
	end

	def show
		@article = Article.friendly.where(active: true).find(params[:id])
	end

end

app/controllers/superuser/articles_controller.rb
# frozen_string_literal: true

module Superuser
  class ArticlesController < Superuser::BaseController
    def index
      @articles = Article.all.page params[:page]
    end

    def new
      @article = Article.new
    end

    def edit
      @article = Article.find(id)
    end

    def active
      @article = Article.find(params[:article_id])
      @article.update_attributes(active: !@article.active)
      respond_to do |format|
        format.js
        format.html { redirect_to root_path}
      end
    end

    def update
      @article = Article.find(id)
      if @article.update_attributes(article_params)
        redirect_to edit_superuser_article_path, notice: "Update successfully"
      else
        render :edit
      end
    end

    def create
      @article = Article.new(article_params)
      if @article.save
        redirect_to superuser_articles_path, notice: "Create successfully"
      else
        render :new
      end
    end

    def destroy
      @article = Article.find id
      @article.destroy
      flash[:notice] = 'Article has been deleted successfully.'
      redirect_to superuser_articles_path
    end

    private

    def id
      params.require(:id)
    end

    def article_params
      params.require(:article).permit(:content,:title, :category_id, :image, :description)
    end

  end
end

app/controllers/superuser/base_controller.rb
# frozen_string_literal: true

module Superuser
  class BaseController < ApplicationController
    layout 'superuser'
    before_action :authenticate_admin_user!, unless: :devise_controller?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.slim
.article-container
  a[href="#{article_path(article)}"]
    img.img-fluid.center-block[src="#{article.image.url}" height="324"]
  .blog-content.bg-white
    h3 = article.title
    p
      | Category :
      a[href="javascript::;"]
        | #{article.category_name}
    p
      | #{article.description}
      a.heading_color[href="#{article_path(article)}"]
        |  Continue Reading
    hr
    p
      = render 'shared/socials/share', article: article
      / span
      /   | Share :
      /   a[href="javascript::;"]
      /     i.fa.fa-facebook.margin_left10[aria-hidden="true"]

      span.pull-right
        | By :
        strong
          | Ngộ

app/views/articles/index.html.slim
#articles
  .container
    .row
      - if @articles.size == 0
        .no-result Không tìm thấy
      - @articles.each do |article|
        .col-md-6
          = render partial: "article", locals: {article: article}
    br
    .row
      .col
        .float-right
          = paginate @articles

app/views/articles/show.html.slim
.container
  .row
    .col-lg-8
      h1.mt-4 = @article.title
      p.lead
        |  by
        a[href="#"]
          | &nbsp Ngộ
      hr
      p
        | Posted on #{@article.created_at.to_s(:date_time)}
      hr
      = image_tag(@article.image.url, class: "img-fluid")
      hr
      .content
        = raw @article.content
      hr
      .fb-comments data-href="#{article_url(@article)}" data-numposts="5"

    .col-md-4
      .card.my-4
        h5.card-header
          | Search
        .card-body
          .input-group
            input.form-control[type="text" placeholder="Search for..."]
            span.input-group-btn
              button.btn.btn-secondary[type="button"]
                | Go!
      .card.my-4
        h5.card-header
          | Categories
        .card-body
          .row
            .col-lg-6
              ul.list-unstyled.mb-0
                li
                  a[href="#"]
                    | Web Design
                li
                  a[href="#"]
                    | HTML
                li
                  a[href="#"]
                    | Freebies
            .col-lg-6
              ul.list-unstyled.mb-0
                li
                  a[href="#"]
                    | JavaScript
                li
                  a[href="#"]
                    | CSS
                li
                  a[href="#"]
                    | Tutorials
      .card.my-4
        h5.card-header
          | Side Widget
        .card-body
          .fb-page data-adapt-container-width="true" data-hide-cover="false" data-href="https://www.facebook.com/nhavoxinh/" data-show-facepile="true" data-small-header="false" data-tabs="timeline"
            blockquote.fb-xfbml-parse-ignore cite="https://www.facebook.com/facebook"
              a href="https://www.facebook.com/facebook"  Facebook

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Ngoblog
    meta content=("width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;") name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      = render 'shared/layouts/header'
    main
      = yield
    / footer
    /   .footer
    /     .container
    /       = render 'shared/layouts/footer'
    = render 'layouts/application/render_js'

app/views/layouts/application/_render_js.html.slim
= render 'shared/scripts/facebook_comment'

app/views/layouts/superuser.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title
      | Scry
    = csrf_meta_tags
    = stylesheet_link_tag    'superuser', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'superuser', 'data-turbolinks-track': 'reload'
    / = favicon_link_tag 'favicon.ico'
  body
    main
      = yield

app/views/shared/layouts/_footer.html.slim
.text-muted Footer

app/views/shared/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
  .container
    a.navbar-brand[href="#"]
      | N.G.O
    button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    #navbarsExampleDefault.collapse.navbar-collapse
      ul.navbar-nav.mr-auto
      /   li.nav-item.active
      /     a.nav-link href="#"
      /       | Home
      /       span.sr-only (current)
      /   li.nav-item
      /     a.nav-link href="#"  Link
      /   li.nav-item
      /     a.nav-link.disabled href="#"  Disabled
      /   li.nav-item.dropdown
      /     a#dropdown01.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="http://example.com"  Dropdown
      /     .dropdown-menu aria-labelledby="dropdown01"
      /       a.dropdown-item href="#"  Action
      /       a.dropdown-item href="#"  Another action
      /       a.dropdown-item href="#"  Something else here
      = form_tag articles_path, method: 'get', class: 'form-inline my-2 my-lg-0' do
        = text_field_tag :search, params[:search], class: "form-control mr-sm-2"
        = submit_tag "Search", name: nil, class: "btn btn-outline-success my-2 my-sm-0"
      / form.form-inline.my-2.my-lg-0
      /   input.form-control.mr-sm-2 aria-label="Search" placeholder="Search" type="text" /
      /   button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search

app/views/shared/scripts/_facebook_comment.html.slim
<div id="fb-root"></div>
javascript:
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v3.0&appId=137574656806655&autoLogAppEvents=1';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // (function(d, s, id) {
  //   var js, fjs = d.getElementsByTagName(s)[0];
  //   if (d.getElementById(id)) return;
  //   js = d.createElement(s); js.id = id;
  //   js.src = 'https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v3.0&appId=1738048343138639&autoLogAppEvents=1';
  //   fjs.parentNode.insertBefore(js, fjs);
  // }(document, 'script', 'facebook-jssdk'));

app/views/shared/socials/_share.html.slim
.shared-socials-share-container
  div style=("display: inline-flex;")
    = social_share_button_tag("", url: article_url(article), desc: article.description)

app/views/superuser/articles/_form.html.slim
.container
	.row
		.col-md-12
			= simple_form_for [:superuser, article] do |a|
				= a.input :category_id, collection: Category.all
				= a.input :image
				= image_tag(article.image.url, class: 'img-fluid') if article.image.present?
				= a.input :title
				= a.input :description
				= a.input :content, as: :summernote
				= a.submit "Submit"

app/views/superuser/articles/active.js.erb
$('.btn-primary').data("article_id", "<%= @article.active%>").text("<%= @article.active ? 'Disable' : 'Active' %>")

app/views/superuser/articles/edit.html.slim
= render partial: 'form', locals: {article: @article}

app/views/superuser/articles/index.html.slim
.container
  .row
    .col-md-12
      table.table.table-responsive
        thead
          tr
            th[scope="col"]
              | #
            th[scope="col"]
              | title
            th[scope="col"]
              | description
            th[scope="col"]
              |
            th[scope="col"]
              |
            th[scope="col"]
              |
        tbody
          - @articles.each_with_index do |article, index|
            tr
              th[scope="row"]
                | #{index}
              td
                | #{article.title}
              td
                | #{article.description}
              td
                = link_to "Edit", edit_superuser_article_path(article), class: "btn btn-success"
              td
                = link_to article.active ? "Disable" : "Active", superuser_article_active_path(article), remote: true, method: :put, class: "btn btn-primary", data: {article_id: article.id}
              td
                = link_to "Delete", superuser_article_path(article), method: :delete,class: "btn btn-danger", data: {confirm: "Are you sure?"}
      = paginate @articles

app/views/superuser/articles/new.html.slim
.container
	.row
		.col-md-12
			= simple_form_for [:superuser, @article] do |a|
				= a.input :category_id, collection: Category.all
				= a.input :image
				= a.input :title
				= a.input :content, as: :summernote
				= a.submit "Submit"